import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Chart as ChartJS, CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend } from 'chart.js';
ChartJS.register(CategoryScale, LinearScale, PointElement, LineElement, Title, Tooltip, Legend);
import { Line } from 'react-chartjs-2';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
   const [data, setData] = useState({
      labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      datasets: [
         {
            label: 'Mentee registration trends',
            fill: true,
            lineTension: 0.1,
            backgroundColor: 'red',
            borderColor: 'rgba(75,192,192,1)',
            borderCapStyle: 'butt',
            borderDash: ['4px'],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: 'rgba(75,192,192,1)',
            pointBackgroundColor: '#000',
            pointBorderWidth: 6,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: 'rgba(75,192,192,1)',
            pointHoverBorderColor: 'rgba(220,220,220,1)',
            pointHoverBorderWidth: 2,
            pointRadius: 1,
            pointHitRadius: 10,
            data: [45, 29, 30, 40, 50, 55, 60, 65, 50, 71, 75, 80],
         },
      ],
   });
   return (
      <div>
         <Head>
            <title>Chart</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main>
            <h3>Chart</h3>
            <div className={styles.chart}>
               <Line data={data} />
            </div>
         </main>
      </div>
   );
};

export default Home;
